package datamodel;

public enum Genre {
    ROMANCE, BIOGRAPHY, CRIME, DRAMA, HISTORY, ADVENTURE, FANTASY,
    WAR, HORROR, MYSTERY, WESTERN, ACTION, SCIFI, FAMILY, COMEDY, THRILLER, MUSICAL, MUSIC, FILMNOIR, ANIMATION;
}
